import { chromium } from '@playwright/test';
import { mkdir } from 'node:fs/promises';
const browser = await chromium.launch({ channel: 'msedge', headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
const errors = [];
page.on('pageerror', e => errors.push(e.message));
page.on('console', m => { if (m.type() === 'error') errors.push(m.text()); });
await page.goto('http://127.0.0.1:5173/', { waitUntil: 'networkidle' });
await page.locator('canvas').waitFor();
await mkdir('test-results', { recursive: true });
await page.screenshot({ path: 'test-results/start-desktop.png', fullPage: true });
await page.getByRole('button', { name: 'START INNINGS' }).click();
await page.waitForTimeout(1700);
await page.screenshot({ path: 'test-results/playing-desktop.png', fullPage: true });
await page.keyboard.press('Escape');
await page.screenshot({ path: 'test-results/paused-desktop.png', fullPage: true });
await page.setViewportSize({ width: 390, height: 844 });
await page.goto('http://127.0.0.1:5173/', { waitUntil: 'networkidle' });
await page.screenshot({ path: 'test-results/start-mobile.png', fullPage: true });
console.log(JSON.stringify({ errors, canvas: await page.locator('canvas').count(), overflow: await page.evaluate(() => document.documentElement.scrollWidth > innerWidth) }));
await browser.close();
if (errors.length) process.exitCode = 1;
